---
language: node_js
node_js:
- '0.10'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -qg bower grunt-cli
- npm install -q
- bower install --force
- bower install --force
after_success:
- "./node_modules/angular-ui-publisher/travis/authentication.sh || exit 0"
- "grunt dist build:gh-pages publish:gh-pages build:bower publish:bower"
script: grunt
env:
  global:
  - REPO="git@github.com:angular-ui/ui-layout.git"